"""Shared test fixtures for christiangeorgelucas/spatial-tools node tests.

Provides:
  - a minimal AxiomContext test double (_TestContext)
  - proto builders for Matrix/Vector/IntVector
  - hand-built point sets with KNOWN geometric structure, used as
    independent oracles (a unit square/cube whose area/volume/hull is
    computable by hand; points on a number line whose nearest neighbor is
    obvious by inspection; collinear points that admit no triangulation) —
    none of these are generated by any randomized routine, so the expected
    answer is derivable independently of the scipy implementation under
    test.
"""
from __future__ import annotations

from gen.axiom_context import SecretStatus
from gen.messages_pb2 import IntVector, Matrix, Vector


class _TestContext:
    class _Logger:
        def debug(self, msg: str, **attrs) -> None: pass
        def info(self, msg: str, **attrs) -> None: pass
        def warn(self, msg: str, **attrs) -> None: pass
        def error(self, msg: str, **attrs) -> None: pass

    class _Secrets:
        def __init__(self, m: dict, revoked: set) -> None:
            self._m = m or {}
            self._revoked = revoked or set()

        def get(self, name: str):
            v = self._m.get(name)
            return (v, True) if v is not None else ("", False)

        def status(self, name: str) -> SecretStatus:
            if name in self._m:
                return SecretStatus.AVAILABLE
            if name in self._revoked:
                return SecretStatus.REVOKED
            return SecretStatus.UNSET

    def __init__(self, secrets_map: dict | None = None, revoked_names: set | None = None) -> None:
        self.log = self._Logger()
        self.secrets = self._Secrets(secrets_map or {}, revoked_names)
        self.execution_id = "test-execution-id"
        self.flow_id = "test-flow-id"
        self.tenant_id = "test-tenant-id"


def make_matrix(rows: list[list[float]]) -> Matrix:
    m = Matrix()
    for row in rows:
        r = m.rows.add()
        r.values.extend(row)
    return m


def make_vector(values: list[float]) -> Vector:
    return Vector(values=values)


def make_int_vector(values: list[int]) -> IntVector:
    return IntVector(values=values)


# ---------------------------------------------------------------------------
# Known-structure fixtures
# ---------------------------------------------------------------------------

# A unit square: area 1, perimeter 4, exactly 2 Delaunay triangles, all 4
# points on the convex hull.
UNIT_SQUARE = [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [1.0, 1.0]]

# A unit cube (8 corners): volume 1, surface area 6, exactly 12 hull
# triangles (2 per face).
UNIT_CUBE = [
    [0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [1.0, 1.0, 0.0],
    [0.0, 0.0, 1.0], [1.0, 0.0, 1.0], [0.0, 1.0, 1.0], [1.0, 1.0, 1.0],
]

# Collinear points — no valid 2D Delaunay triangulation or 2D convex hull
# (rank-deficient: all points lie on a single line, no positive-area
# region exists).
COLLINEAR_2D = [[0.0, 0.0], [1.0, 0.0], [2.0, 0.0], [3.0, 0.0]]

# Points on a 1D number line (embedded as 1-column points) with an obvious,
# hand-verifiable nearest neighbor: querying 11.0 against {0, 10, 20, 30}
# must return index 1 (value 10.0, distance 1.0).
LINE_1D = [[0.0], [10.0], [20.0], [30.0]]

# A 5-point plus-sign pattern centered at the origin: obviously symmetric,
# used for KNN-graph / radius / pairs sanity checks with hand-countable
# answers. Distance from center (index 0) to each arm is exactly 1.0;
# distance between adjacent arms is sqrt(2).
PLUS_SIGN = [[0.0, 0.0], [1.0, 0.0], [-1.0, 0.0], [0.0, 1.0], [0.0, -1.0]]
